version: 2.1

jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: echo
          command: echo "This config is defined in NEW-checkout-repo"

workflows:
  do_some_stuff:
    jobs:
      - myjob
